# This is a basic workflow to help you get started with Actions

name: Amazon EKS Helm Deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # You may pin to the exact commit or the version.
      # uses: dgrezza/action-eks-helm-deploy@36d4862bc4c171b5d4643a942cb0a9af5ee9c071
      uses: dgrezza/action-eks-helm-deploy@v0.1.7
      with:
        # AWS credentials used to login to eks.
        aws-secret-access-key: 
        # AWS credentials used to login to eks.
        aws-access-key-id: 
        # AWS region to use (default: ap-southeast-1)
        aws-region: # default is ap-southeast-1
        # EKS cluster name.
        cluster-name: 
        # EKS cluster admin role arn.
        cluster-role-arn: # optional
        # Comma separates list of helm values files.
        config-files: # optional
        # Kubernetes namespace to use.
        namespace: # optional
        # Comma separated list of value sets for helms. e.x: key1=value1,key2=value2
        values: # optional
        # Name of the helm deploy.
        name: # optional
        # The path of the chart.
        chart-path: # optional
        # docker image tag for new deployment
        image-tag: # optional
        # application name for deployment
        application-name: 
